# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e3c8439974713471fd4161a308828e8ba377824c26b5bfc2af19abd6fc2dfbef6d967fca569dcd21080d974bbe469cc78e9f78d44e12ce53533668a509f4e62

test:
  secret_key_base: 53978355800635e06e0da6edda4f08cac3aa5ee1417fe3225487bf8ea9d1bb03d4cdd77403efec85d6f1df90e0cb25aedb5d80d47fcc20bd9e1d21b72ccf8988

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
